/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as DocsBuildATodoAppWithCodemindRouteImport } from './routes/docs.build-a-todo-app-with-codemind'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPProjectIdIndexRouteImport } from './routes/_authenticated/p.$projectId.index'
import { Route as AuthenticatedPProjectIdThreadIdRouteImport } from './routes/_authenticated/p.$projectId.$threadId'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DocsBuildATodoAppWithCodemindRoute =
  DocsBuildATodoAppWithCodemindRouteImport.update({
    id: '/docs/build-a-todo-app-with-codemind',
    path: '/docs/build-a-todo-app-with-codemind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPProjectIdIndexRoute =
  AuthenticatedPProjectIdIndexRouteImport.update({
    id: '/p/$projectId/',
    path: '/p/$projectId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPProjectIdThreadIdRoute =
  AuthenticatedPProjectIdThreadIdRouteImport.update({
    id: '/p/$projectId/$threadId',
    path: '/p/$projectId/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/build-a-todo-app-with-codemind': typeof DocsBuildATodoAppWithCodemindRoute
  '/p/$projectId/$threadId': typeof AuthenticatedPProjectIdThreadIdRoute
  '/p/$projectId/': typeof AuthenticatedPProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/build-a-todo-app-with-codemind': typeof DocsBuildATodoAppWithCodemindRoute
  '/': typeof AuthenticatedIndexRoute
  '/p/$projectId/$threadId': typeof AuthenticatedPProjectIdThreadIdRoute
  '/p/$projectId': typeof AuthenticatedPProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/build-a-todo-app-with-codemind': typeof DocsBuildATodoAppWithCodemindRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/p/$projectId/$threadId': typeof AuthenticatedPProjectIdThreadIdRoute
  '/_authenticated/p/$projectId/': typeof AuthenticatedPProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/students'
    | '/api/chat'
    | '/docs/build-a-todo-app-with-codemind'
    | '/p/$projectId/$threadId'
    | '/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/students'
    | '/api/chat'
    | '/docs/build-a-todo-app-with-codemind'
    | '/'
    | '/p/$projectId/$threadId'
    | '/p/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/students'
    | '/api/chat'
    | '/docs/build-a-todo-app-with-codemind'
    | '/_authenticated/'
    | '/_authenticated/p/$projectId/$threadId'
    | '/_authenticated/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentsRoute: typeof StudentsRoute
  ApiChatRoute: typeof ApiChatRoute
  DocsBuildATodoAppWithCodemindRoute: typeof DocsBuildATodoAppWithCodemindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/docs/build-a-todo-app-with-codemind': {
      id: '/docs/build-a-todo-app-with-codemind'
      path: '/docs/build-a-todo-app-with-codemind'
      fullPath: '/docs/build-a-todo-app-with-codemind'
      preLoaderRoute: typeof DocsBuildATodoAppWithCodemindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/p/$projectId/': {
      id: '/_authenticated/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof AuthenticatedPProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$projectId/$threadId': {
      id: '/_authenticated/p/$projectId/$threadId'
      path: '/p/$projectId/$threadId'
      fullPath: '/p/$projectId/$threadId'
      preLoaderRoute: typeof AuthenticatedPProjectIdThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPProjectIdThreadIdRoute: typeof AuthenticatedPProjectIdThreadIdRoute
  AuthenticatedPProjectIdIndexRoute: typeof AuthenticatedPProjectIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPProjectIdThreadIdRoute: AuthenticatedPProjectIdThreadIdRoute,
  AuthenticatedPProjectIdIndexRoute: AuthenticatedPProjectIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentsRoute: StudentsRoute,
  ApiChatRoute: ApiChatRoute,
  DocsBuildATodoAppWithCodemindRoute: DocsBuildATodoAppWithCodemindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
